---

# Here we use the Docker Desktop built-in Kubernetes cluster,
# which has a default domain of 'kubernetes.docker.internal'.
# You must use a domain that is suitable for your cluster.
jo_ingress_domain: kubernetes.docker.internal
# Secrets and certificate issuer for you rJupyter URLs.
# But not defining a secret you use the one provided by the Data Manager.
jo_ingress_tls_secret: ''
jo_ingress_cert_issuer: letsencrypt-nginx-production
# The Data Manager Kubernetes name
# (used as a suffix for the namespace unless it's explicitly named)
jo_dmapi_name: local
jo_dmapi_namespace: data-mamager-api
# The Operator image tag
jo_image_tag: 1.1.4

# The Kubernetes config file (yours will be different)
jo_kubeconfig: ~/k8s-config/config-local
