---

# Check the Data Manager Namespace and Service Account exists...

- name: Get Data Manager Namespace ({{ jo_dmapi_namespace }})
  kubernetes.core.k8s_info:
    kind: Namespace
    name: "{{ jo_dmapi_namespace }}"
  register: ns_result

- name: Assert Namespace ({{ jo_dmapi_namespace }})
  assert:
    that:
    - ns_result.resources|length == 1

- name: Get Data Manager ServiceAccount
  kubernetes.core.k8s_info:
    kind: ServiceAccount
    name: data-manager
    namespace: "{{ jo_dmapi_namespace }}"
  register: sa_result

- name: Assert ServiceAccount
  assert:
    that:
    - sa_result.resources|length == 1

- name: Deploy Data Manager API Operator RBAC
  kubernetes.core.k8s:
    definition: "{{ lookup('template', 'rbac-data-manager.yaml.j2') }}"
    wait: yes

# Now we can (safely) deploy the operator

- name: Deploy CRD
  kubernetes.core.k8s:
    definition: "{{ lookup('template', 'crd.yaml.j2') }}"
    wait: yes

- name: Deploy Data Manager API RBAC
  kubernetes.core.k8s:
    definition: "{{ lookup('template', '{{ item }}.yaml.j2') }}"
    wait: yes
  loop:
  - rbac-data-manager

- name: Deploy objects to operator Namespace ({{ jo_namespace }})
  kubernetes.core.k8s:
    definition: "{{ lookup('template', '{{ item }}.yaml.j2') }}"
    wait: yes
  loop:
  - namespace
  - sa
  - rbac
  - deployment
