---

- include_tasks: prep.yaml

- name: Assert operator version defined
  assert:
    that:
    - jo_image_tag|length > 0
    - jo_image_tag != 'SetMe'

- name: Deploy using Kubernetes config
  block:

  - include_tasks: deploy.yaml
    when: jo_state|string == 'present'
  - include_tasks: undeploy.yaml
    when: jo_state|string == 'absent'

  module_defaults:
    group/k8s:
      kubeconfig: "{{ jo_kubeconfig }}"
