---
name: build

# Actions that take place on branches
# or are driven by pull-requests to the main/master branch.
# Here we build container images but don't push them
# and therefore do not require docker credentials.

# -----------------
# Control variables (GitHub Secrets)
# -----------------
#
# (n/a)
#
# -----------
# Environment (GitHub Environments)
# -----------
#
# Environment         (n/a)

on:
  push:
    branches-ignore:
    - 'main'
  pull_request:
    branches:
    - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r build-requirements.txt
        pip install -r requirements.txt
        ansible-galaxy install -r requirements.yaml
    - name: Lint
      run: |
        yamllint .
        find . -type f -name '*.yaml.j2' -exec yamllint {} +
        ansible-lint
    - name: Build
      uses: docker/build-push-action@v2
      with:
        context: operator
