---
name: build latest

# Actions on the main/master branch for every change.

# -----------------
# Control variables (GitHub Secrets)
# -----------------
#
# At the GitHub 'organisation' or 'project' level you must have the following
# GitHub 'Repository Secrets' defined (i.e. via 'Settings -> Secrets'): -
#
# DOCKERHUB_USERNAME
# DOCKERHUB_TOKEN
#
# -----------
# Environment (GitHub Environments)
# -----------
#
# Environment         (n/a)

on:
  push:
    branches:
    - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r build-requirements.txt
        pip install -r requirements.txt
        ansible-galaxy install -r requirements.yaml
    - name: Lint
      run: |
        yamllint .
        find . -type f -name '*.yaml.j2' -exec yamllint {} +
        ansible-lint
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: operator
        push: true
        tags: informaticsmatters/data-manager-jupyter-operator:latest
